project:
  type: website
  output-dir: docs

website:
  title: "First Stride Coaching"
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    right:
      - href: index.qmd
        text: Home
      - href: plans.qmd
        text: Coaching Details
      - href: about.qmd
        text: Coaches
      

format:
  html:
    theme: [styles.scss, cosmo]
    anchor-sections: false

editor: visual

