project:
  type: website
  output-dir: docs

website:
  title: "First Stride Coaching"
  favicon: images/logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

