project:
  type: website
  output-dir: docs

website:
  title: "First Stride Coaching"
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - text: How it Works
      - text: Meet the Coach

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

