project:
  type: website
  output-dir: docs
  resources: 
    - CNAME

website:
  title: "First Stride Coaching"
  favicon: images/fsclogo.png
  google-analytics: "G-81LWDQC49S"
  navbar:
    logo: images/fsclogo.png
    right:
      - href: index.qmd
        text: Home
      - href: plans.qmd
        text: Coaching Details
      - href: about.qmd
        text: Coaches
      - href: posts.qmd
        text: Blog
      

format:
  html:
    theme: [styles.scss, cosmo]
    anchor-sections: false

editor: visual

